# Generated by Django 6.1.1 on 2026-10-03 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(unique=True, verbose_name='Номер стола')),
                ('equipment_info', models.TextField(blank=True, help_text="Например: Монитор 27', клавиатура, док-станция", null=True, verbose_name='Установленное оборудование')),
                ('is_occupied', models.BooleanField(default=False, verbose_name='Стол занят')),
            ],
            options={
                'verbose_name': 'Рабочее место',
                'verbose_name_plural': 'Рабочие места',
                'ordering': ['table_number'],
            },
        ),
    ]
