# Generated by Django 6.1.1 on 2026-10-03 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeimage',
            name='image',
            field=models.FileField(upload_to='employee_gallery/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество (при наличии)'),
        ),
    ]
