# Generated by Django 6.1.1 on 2026-10-07 05:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employeeimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата приёма на работу'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='desk_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер стола'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='role',
            field=models.CharField(choices=[('backend', 'Бэкенд-разработчик'), ('frontend', 'Фронтенд-разработчик'), ('qa', 'Тестировщик'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Должность'),
        ),
    ]
